### ISSUE TITLE
It's a copy from Plugin.Toast.Abstractions

### ISSUE THREAD

**Issue by didourebai** [ishrakland/Toast#1]
Try to create you own DLL full developed not a copy from another!!
This is a copy from Plugin.Toast.Abstractions you just use it as described in this link I can't see the the intake! This dll has a copyright so you can't create a dll by your name!!!!

**Comment by ishrakland** [comment]
If you mean Toasts.Forms.Plugin . it Shows Notifications.
If you mean Plugin.Toast : It's also my plugin 
Before attacking me  you should document your self and verify the owner.
