### ISSUE TITLE
UnhandledException on UWP

### ISSUE THREAD

**Issue by rblanca** [ishrakland/Toast#11]
Hi, I'm using your great nuget but I have a this problem when you try to use it on UWP.

{"Could not load file or assembly 'Plugin.Toast, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)":"Plugin.Toast, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null"}

Installed Version 2.1.2

**Comment by ishrakland** [comment]
hi , probably your UWP project is Netstandard 1.0 and not 2.0 . configure your UWP Project  same a the sample project

**Comment by rblanca** [comment]
Thanks ishrkland 4 your answer....i'll try what you said (It also happend with your sample project too)

**Comment by RossWlodarczyk** [comment]
I have the exact same issue. My target framework is 2.0 as below.

<TargetFramework>netstandard2.0</TargetFramework>

**Comment by jdinnen** [comment]
I was unable to get either the Sample or my project to work on UWP. I am already on Standard 2.0.

**Comment by qiukeren** [comment]
just call `CrossToastPopUp.Current.ShowToastMessage("12312312313");`

System.IO.FileLoadException: Could not load file or assembly 'Plugin.Toast, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

get the same return message.

android is ok,
UWP throws an exception,
ios not tested.

**Comment by SunshineSpring666** [comment]
Same exception encountered on UWP, tested with latest version of Xamarin.Forms.

**Comment by HelenMamalaki** [comment]
Same exception thrown for me on UWP. (Works fine on Android and iOS.)

Xamarin.Forms 4.6.0.967
Targeting Win10 Fall Creators Update (16299) 
Plugin.Toast v2.1.2

Has anyone found a workaround for this?

**Comment by ishrakland** [comment]
You need xamarin forms 4.7.1351 and last Toast.plugin version 2.2.0

**Comment by zizusoft** [comment]
This issues does not look like it was ever resolved?

**Comment by elizeon** [comment]
I am having this issue even using Xamarin forms 4.7.1351 and Toast.plugin version 2.2.0 as recommended.
My project is using .Netstandard 2.0 and target version is Windows 10, version 1903
