### ISSUE TITLE
2.1.3 is broken

### ISSUE THREAD

**Issue by alessandrofrancesconi** [ishrakland/Toast#15]
After upgrading from 2.1.2 to [2.1.3](https://www.nuget.org/packages/Plugin.Toast/2.1.3), the `Plugin.Toast` namespace is not found anymore, as well as `CrossToastPopUp` class.

**Comment by ederjbezerra** [comment]
Same problem here.

**Comment by AntvissMedia** [comment]
+1

**Comment by raulandresduque** [comment]
+1

**Comment by Rabosa616** [comment]
+1

**Comment by ishrakland** [comment]
check new version 2.2.0, you need xamarin forms 4.7.1351
