### ISSUE TITLE
Is there any chance to work on Windows applications?

### ISSUE THREAD

**Issue by pantelisGeo90** [ishrakland/Toast#4]
Hello, nice work on this one.
I've tried running it on a Windows app (on xamarin.forms) but it trows an error and the app exits. I did notice on your readme says `Windows Phone`.
Nevertheless when i execute `CrossToastPopUp.IsSupported` on a windows app it returns true.
It works fine on Android. Haven't tried on iOS but i suppose it will also work fine.

**Comment by ishrakland** [comment]
Hello 

Thank you for you feedback.
This plugin is tested on iOS and Android. I added an implementation for Windows Phone but it is not tested I will work on it in future versions.

**Comment by ishrakland** [comment]
Please check the new version of the package 2.1.2
