### ISSUE TITLE
Could we have a way to specify the delay before the toast disappears?

### ISSUE THREAD

**Issue by ngorse** [ishrakland/Toast#6]
This is not an issue, just a request for enhancement. Thanks!

**Comment by ishrakland** [comment]
i wil work for that in next versions

**Comment by jirimatejka** [comment]
I implemented this change yesterday, there is a pending pull request now:
https://github.com/ishrakland/Toast/pull/7

Jiri

**Comment by ishrakland** [comment]
Thank you so much , I will  test your  commit and give you a feedback.

**Comment by ishrakland** [comment]
Please check the new version of the package
